version: 2.1
orbs:
  node: circleci/node@4.7.0

commands:
  setup_git:
    steps:
      - add_ssh_keys:
          fingerprints:
            - '85:6e:5d:a6:3b:97:82:a2:6b:de:20:67:1f:f8:ba:d0'
      - run:
          name: Setup git config global
          command: |
            git config user.email "dev@codetot.com"
            git config user.name "CODE TOT JSC"

jobs:
  test:
    executor:
      name: node/default
      tag: '14.17.6'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
  build:
    executor:
      name: node/default
      tag: '14.17.6'
    steps:
      - checkout
      - setup_git
      - node/install-packages
      - run:
          name: Build assets
          command: npm run build
      - run:
          name: Commit if assets changes
          command: |
            if [ -n "$(git status --porcelain)" ]; then
              git add .
              git commit -m "Process styles and scripts [skip ci]"
              git push origin HEAD:${CIRCLE_BRANCH}
              exit 0
            else
              exit 0
            fi
  release:
    executor:
      name: node/default
      tag: '14.17.6'
    steps:
      - checkout
      - setup_git
      - run:
          name: Remove source
          command: |
            rm -rf assets/js/*.js.LICENSE.txt src/ package.json package-lock.json
            rm -rf .babelrc .browserslistrc .eslintrc.js .prettierignore .stylelintrc
            rm -rf components/*/src/ components/*/.browserslistrc components/*/.eslintrc.js components/*/.prettierignore components/*/.stylelintrc
      - run:
          name: Commit assets changes
          command: |
            git add .
            git commit -m "Prepare production package"
            git push origin HEAD:production-temp --force
      - run:
          name: Merge to branch production
          command: |
            git reset --hard origin/production
            git merge origin/production-temp --no-ff --no-edit -m "Release package"
            git push origin HEAD:production
            git push origin :production-temp

workflows:
  test_assets:
    jobs:
      - test:
          filters:
            branches:
              only: /(feature|bugfix|hotfix)\/?(.*)/
  build_assets:
    jobs:
      - build:
          filters:
            branches:
              only: /(develop|feature\/ci)/
  release_package:
    jobs:
      - release:
          filters:
            branches:
              only: master
